export enum OrderStatus {
  CREATED = 'CREATED',
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  ON_THE_WAY = 'ON_THE_WAY',
  ARRIVED = 'ARRIVED',
  SERVICE_STARTED = 'SERVICE_STARTED',
  DONE = 'DONE',
  CANCELED = 'CANCELED',
}
